### PR TITLE
openfl 4 compatibility changes

### PR DESCRIPTION
**Pull request by Beeblerox**

### CODE REVIEW

**Comment by starry-abyss** [comment]
Great work!

Cannot compile my project with this though:

on neko:
```
Running Pre-Build Command Line...
cmd: "D:\build\HaxeToolkit\haxe/haxelib" run lime build "Project.xml" neko -debug -Dfdb
Type not found : ApplicationMain
Build halted with errors.
```

and on flash:
```
D:/build/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxBackdrop.hx:10: characters 7-44 : Type not found : flixel.graphics.tile.FlxDrawTilesItem
```

**Comment by Beeblerox** [comment]
@starry-abyss let me look into this

**Comment by Beeblerox** [comment]
@starry-abyss strange, since `FlxBackdrop` doesn't have `FlxDrawTilesItem` import or references.
What versions of haxe, openfl, lime and hxcpp are you using?

I'm using latest dev versions of openfl and lime
Haxe 3.3.0-RC1
hxcpp 3.3.49

**Comment by starry-abyss** [comment]
@Beeblerox My bad, I was using openfl3 branch. Now instead of FlxBackdrop error on flash I get the same as on neko.

develop branches of openfl and lime
Haxe 3.2.0 (O_O going to update it to 3.2.1, thought it was auto-updated with haxelib)
hxcpp 3.3.49

**Comment by Beeblerox** [comment]
Maybe you're using Haxe 3.2.0 because flixel-ui doesn't work with Haxe 3.2.1 on native targets

**Comment by starry-abyss** [comment]
I don't know, now it's 3.2.1, and `Type not found : ApplicationMain` remained.
Is OpenFl4 incompatible with Haxe 3.2 ?

**Comment by Gama11** [comment]
>Is OpenFl4 incompatible with Haxe 3.2 ?

No.

**Comment by starry-abyss** [comment]
Do I also need to update some packages like lime-tools?
Looks like I can't rebuild lime:
```
./src/audio/openal/OpenALBindings.cpp(1239) : error C3861: 'alcDevicePauseSOFT':
 identifier not found
./src/audio/openal/OpenALBindings.cpp(1257) : error C3861: 'alcDeviceResumeSOFT'
: identifier not found
```

**Comment by Gama11** [comment]
lime-tools isn't a separate haxelib anymore, it's been merged into Lime a while ago.

**Comment by starry-abyss** [comment]
Things flipped! I removed lime-tools and did `lime rebuild tools`. Now I have FlxBackdrop issue back, and no ApplicationMain one.

**Comment by starry-abyss** [comment]
And I'm pretty sure my flixel-addons package is latest dev

**Comment by starry-abyss** [comment]
@Beeblerox @Gama11 
So I upgraded to Haxe 3.3rc1. Also after a fix in dev branch of lime, I've rebuilt it.

FlxBackdrop issue update: simply commenting out the import line gives this instead:
[neko/flash]
```
D:/build/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxBackdrop.hx:178: characters 19-40 : flixel.FlxCamera has no field startQuadBatch
```

Also, I'm getting these new issues on different projects:
[neko - all projects]
```
D:/build/HaxeToolkit/haxe/lib/flixel/separate-render/flixel/util/FlxDestroyUtil.hx:131: characters 4-27 : Cannot access field or identifier glProgram for writing
```

[neko/flash - all projects]
```
source/tiled/TiledImporter.hx:160: characters 5-26 : flixel.tile.FlxTilemap has no field useScaleHack
```

Similar to FlxBackdrop:
[neko/flash]
```
D:/build/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/effects/FlxClothSprite.hx:9: characters 7-48 : Type not found : flixel.graphics.tile.FlxDrawTrianglesItem
```
After commenting out ^:
```
D:/build/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/effects/FlxClothSprite.hx:79: characters 23-38 : Type not found : DrawData
```

One of my projects runs fine on Flash, but crashes on state switch with error:
```
ArgumentError: Error #2015: Invalid BitmapData.
	at flash.display::BitmapData/get width()
	at flixel.graphics::FlxGraphic/set_bitmap()[D:\build\HaxeToolkit\haxe\lib\flixel\separate-render\flixel\graphics\FlxGraphic.hx:646]
	at flixel.graphics::FlxGraphic()[D:\build\HaxeToolkit\haxe\lib\flixel\separate-render\flixel\graphics\FlxGraphic.hx:406]
	at flixel.graphics::FlxGraphic$/createGraphic()[D:\build\HaxeToolkit\haxe\lib\flixel\separate-render\flixel\graphics\FlxGraphic.hx:270]
	at flixel.graphics::FlxGraphic$/fromBitmapData()[D:\build\HaxeToolkit\haxe\lib\flixel\separate-render\flixel\graphics\FlxGraphic.hx:139]
	at flixel.system.frontEnds::BitmapFrontEnd/add()[D:\build\HaxeToolkit\haxe\lib\flixel\separate-render\flixel\system\frontEnds\BitmapFrontEnd.hx:149]
	at flixel::FlxSprite/loadGraphic()[D:\build\HaxeToolkit\haxe\lib\flixel\separate-render\flixel\FlxSprite.hx:338]
	at PlayState/LoadAnimations()[D:\projects\ld35-shapeshift\source\PlayState.hx:254]
	at PlayState/create()[D:\projects\ld35-shapeshift\source\PlayState.hx:599]
	at flixel::FlxGame/switchState()[D:\build\HaxeToolkit\haxe\lib\flixel\separate-render\flixel\FlxGame.hx:646]
	at flixel::FlxGame/update()[D:\build\HaxeToolkit\haxe\lib\flixel\separate-render\flixel\FlxGame.hx:736]
	at flixel::FlxGame/step()[D:\build\HaxeToolkit\haxe\lib\flixel\separate-render\flixel\FlxGame.hx:686]
	at flixel::FlxGame/onEnterFrame()[D:\build\HaxeToolkit\haxe\lib\flixel\separate-render\flixel\FlxGame.hx:553]
```
I can send you the project ^ sources if you would like (they are a mess, though).

Most of the issues can be got with the following project: 
https://github.com/starry-abyss/ld34

**Comment by Beeblerox** [comment]
@starry-abyss thank you for project example. i'll test code with it tonight. If you want to send me code of your project for further testing you can send it to zaphy[at]yandex[dot]ru.

**Comment by Beeblerox** [comment]
@starry-abyss i've compiled your "ld34" project, just had to change 1 line: 
```
FlxG.camera.follow(player, PLATFORMER, null, 4);
```
to 
```
FlxG.camera.follow(player, PLATFORMER, 4);
```

are you sure that you're using proper versions of flixel and flixel-addons?

**Comment by starry-abyss** [comment]
I'm not sure what proper versions are, but I use separate-render branch of your 'flixel' fork + dev branch of the official 'flixel-addons'. Is it not the right way to go?

**Comment by starry-abyss** [comment]
As for the game that crashes on state switch, I found that it crashed on legacy too. May be Haxe 3.3rc1 issue, so irrelevant :-(

**Comment by starry-abyss** [comment]
Sorry, I didn't notice that I was commenting in addons repo... Switched to your fork in addons too now.

This problem remained on neko:
```
D:/build/HaxeToolkit/haxe/lib/flixel/separate-render/flixel/util/FlxDestroyUtil.hx:131: characters 4-27 : Cannot access field or identifier glProgram for writing
```

Also there are crashes and stuff, but I want to downgrade Haxe to 3.2 first to get a clearer picture.
